hope

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -11,25 +11,72 @@ pool:
 variables:
   runEndToEnd: ${{ne(variables['Build.Reason'], 'PullRequest')}}
 
-stages:
-  - stage: Stage1
-    jobs:
-      - job: Job1
-        steps:
-         - bash: echo "Job1"
-      - job: Job2
-        steps:
-          - bash: write-error "Job2 error"
+# ---------------------------------
 
-  - stage: Stage2
-    dependsOn: Stage1
-    condition: always()
-    jobs:
-      - job: Job3
-        condition: in(stageDependencies.Stage1.Job1.result, 'Succeeded')
-        steps:
-          - bash: echo "Job3"
-      - job: Job4
-        condition: in(stageDependencies.Stage1.result, 'Succeeded')
-        steps:
-          - bash: echo "Job4"
+stages:
+- stage: BuildStage
+  displayName:  🏗 Build Stage
+  dependsOn: []
+
+  jobs:
+  # this will create an error
+  - job: HelloWorld
+    displayName: Hello World
+    steps:
+    - script: |
+        echo "Build reason: ${{variables['Build.Reason']}}"
+        echo "Run e2e tests? ${{variables['runEndToEnd']}}"
+
+# ---------------------------------
+
+- stage: IntegrationTestsStage
+  displayName: 🧪 Run integration tests
+  dependsOn: [ 'BuildStage' ]
+  condition: succeeded('BuildStage')
+
+  jobs:
+  - job: FeedbackIntegrationTests
+    displayName: Feedback Integration Tests
+    steps:
+    - bash: exit 1
+    - task: PowerShell@2
+      displayName: Feedback
+      inputs:
+        targetType: inline
+        script: Write-Host 'Hello, World from Integration Tests stage!'
+
+#---------------------------------
+
+- stage: EndToEndTestsStage
+  displayName: 🤖 Run End to End tests
+  dependsOn: [ 'BuildStage' ]
+  condition: |
+    and(
+      eq(variables.runEndToEnd, 'true'), 
+      succeeded('BuildStage')
+      )
+    
+  jobs:
+  - job: Feedback
+    steps:
+    - task: PowerShell@2
+      displayName: Feedback
+      inputs:
+        targetType: inline
+        script: Write-Host 'Hello, World from end 2 end stage!'         
+        
+# ---------------------------------
+
+- stage: ResultStage
+  displayName: 🚀 Build Result
+  dependsOn: [ 'IntegrationTestsStage', 'EndToEndTestsStage' ]
+  condition: succeededOrFailed()
+  jobs:
+  - job: ResultJob
+    displayName: 🚀 Build Results
+    condition: ne(stageDependencies.IntegrationTestsStage.FeedbackIntegrationTests.result, 'Succeeded')
+    steps:
+    - checkout: none
+    - script: echo "Build failed"
+      displayName: Build Failed
+      
